#!/bin/bash

BRANCH="master"

if ! which git; then
	echo "Error: please install git first."
	exit 1
fi

cd ~

if ! git clone --depth 1 https://github.com/gauravmm/dotdotdot.git .dotdotdot; then
	echo "Error: cannot clone repository, try installing manually."
	exit 1
fi

cd .dotdotdot
chmod u+x dotdotdot update

git checkout "$BRANCH"
git remote remove origin
git remote add origin git@github.com:gauravmm/dotdotdot.git
git push -u origin "$BRANCH"

./dotdotdot
