#!/bin/bash

if ! which git ; then 
    echo "Error: please install git first."
    exit 1
fi

cd ~

if ! git clone --depth 1 git@github.com:gauravmm/dotdotdot.git .dotdotdot ; then
    echo "Error: cannot clone repository, try installing manually."
    exit 1
fi

cd .dotdotdot
chmod u+x dotdotdot update
./dotdotdot
