$schema: >-
  https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: path
        style: plain
        background: "#303030"
        foreground: "#91ddff"
        properties:
          style: unique
        template: >-
          {{ if gt .StackCount 0 }}<#000000,#91ddff><b> {{ .StackCount }} </b></><#91ddff,#303030></>{{ end }}
          <b>{{ path .Path .Location }}</b> 

      - type: git
        style: diamond
        # Add a caret separator at the start. The trailing separator is placed at the end of the segments.
        leading_diamond: <#707070></>
        trailing_diamond: ""
        background: "#303030"
        foreground_templates:
          - "{{ if or (.Working.Changed) (.Staging.Changed) }}#ff9248{{ end }}"
          - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}"
          - "{{ if gt .Ahead 0 }}#91ddff{{ end }}"
          - "{{ if gt .Behind 0 }}#c184e0{{ end }}"
          - "#5de96f"
        properties:
          branch_ahead_icon: ↑
          branch_behind_icon: ↓
          branch_gone: ≢
          branch_icon: ""
          branch_identical_icon: ≡
          cherry_pick_icon: "✓ "
          commit_icon: "▷ "
          fetch_status: true
          merge_icon: "◴ "
          no_commits_icon: "[no commits]"
          rebase_icon: "Ɫ "
          tag_icon: "▶ "
        template: " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} │{{ end }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} {{ .StashCount }}{{ end }} "

      - type: text
        style: plain
        template: 
        foreground: "#303030"

  - type: prompt
    alignment: right
    segments:
      - type: status
        style: powerline
        powerline_symbol: 
        invert_powerline: true
        background: "#ff8080"
        foreground: "#ffffff"
        template: "{{ if or (eq .Code 0) (eq .Code 127) (eq .Code 130) }}{{ else }} <b>{{ .String }}</b> {{ end }}"

      - type: text
        style: plain
        template: 
        foreground: "#303030"

      - type: executiontime
        style: diamond
        trailing_diamond: <#707070></>
        foreground: "#707070"
        background: "#303030"
        properties:
          style: round
          threshold: 1000

      - type: python # TODO: Update this.
        style: diamond
        trailing_diamond: <#707070></>
        foreground: "#FFD43B"
        background: "#303030"
        template: >-
           {{ if .Error -}}
            <#ff8080> {{ .Error }}</>
          {{- else -}}
            {{ if .Venv -}}{{ .Venv }}{{- else -}}{{ .Full }}{{- end -}}
          {{- end }}   

      - type: session
        style: diamond
        trailing_diamond: <#707070></>
        background: "#303030"
        foreground_templates:
          - "{{ if .Root -}}#ff8080{{ end }}"
          - "{{ if .SSHSession -}}#007acc{{ end }}"
          - "#707070"
        template: >-
          {{ if .Root }} {{ end }}
          {{ if .SSHSession }} {{ end }}
          {{ if or .Root .SSHSession }}{{ .UserName }}@{{ .HostName }}{{ end }}

      - type: time
        style: plain
        background: "#303030"
        foreground: "#59909E"
        properties:
          time_format: "15:04:05"
        template: " {{ .CurrentDate | date .Format }} "

  - type: prompt
    alignment: left
    segments:
      - foreground: "#ffffff"
        style: plain
        template: ❯
        type: text

ignored_return_codes:
  - 0
  - 127
  - 130
final_space: true
version: 3
