$schema: >-
  https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: path
        style: plain
        background: "#303030"
        foreground: "#91ddff"
        properties:
          style: unique
        template: " <b>{{ path .Path .Location }}</b> "

      - type: git
        style: diamond
        # Add a caret separator at the start. The trailing separator is placed at the end of the segments.
        leading_diamond: <#707070></>
        trailing_diamond: ""
        background: "#303030"
        foreground_templates:
          - "{{ if or (.Working.Changed) (.Staging.Changed) }}#ff9248{{ end }}"
          - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}"
          - "{{ if gt .Ahead 0 }}#89d1dc{{ end }}"
          - "{{ if gt .Behind 0 }}#c5b6ad{{ end }}"
          - "#5de96f"
        properties:
          branch_ahead_icon: ↑
          branch_behind_icon: ↓
          branch_gone: ≢
          branch_icon: " "
          branch_identical_icon: ≡
          cherry_pick_icon: "✓ "
          commit_icon: "▷ "
          fetch_status: true
          merge_icon: "◴ "
          no_commits_icon: "[no commits]"
          rebase_icon: "Ɫ "
          tag_icon: "▶ "
        template: " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} │{{ end }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} {{ .StashCount }}{{ end }} "

      - type: text
        style: plain
        template: 
        foreground: "#303030"

  - type: prompt
    alignment: right
    segments:
      - type: status
        style: powerline
        powerline_symbol: 
        invert_powerline: true # Show it leftwards.
        background: "#ff8080"
        foreground: "#ffffff"
        template: "{{ if or (eq .Code 0) (eq .Code 127) }}{{ else }} {{ .String }} {{ end }}"

      - type: executiontime
        style: powerline
        powerline_symbol: 
        invert_powerline: true
        foreground: "#707070"
        background: "#303030"
        template: " {{ .FormattedMs }} "
        properties:
          threshold: 2000
          style: round

      - type: session
        style: powerline
        powerline_symbol: 
        invert_powerline: true
        foreground_templates:
          - "{{ if .Root -}}#ff8080{{ end }}"
          - "{{ if .SSHSession -}}#007acc{{ end }}"
          - "#757575"
        template: >-
          {{ if .Root }} {{ end }}
          {{ if .SSHSession }} {{ end }}
          {{ if or .Root .SSHSession }}{{ .UserName }}@{{ .HostName }}{{ end }}

      - type: time
        style: powerline
        powerline_symbol: 
        invert_powerline: true
        background: "#303030"
        foreground: "#59909E"
        properties:
          time_format: "15:04:05"
        template: " {{ .CurrentDate | date .Format }} "

  - type: prompt
    alignment: left
    segments:
      - foreground: "#ffffff"
        style: plain
        template: ❯
        type: text

transient_prompt:
  background: transparent
  foreground: "#ffffff"
  template: "{{ .Shell }} {{ .Code }} {{ .String }}> "

final_space: true
version: 3
